import Head from "next/head";
import Image from "next/image";

import Form1 from "../components/Form1";
import React from "react";

export default function Home() {
const [groups,setGroups] = React.useState({
name:string,
contents:[
  tasks[]
]
group.content.push(task)
task : {
  content:string,
group:string,
isComplete?
}

})
const [tasks,setTasks] = React.useState([])


React.useEffect(()=>{

  organizeGroup(
    //lop through tasks,
    //assing to group

setGroups({newGroups})
  )
},[tasks])

//create task with new group
//


const handleTaskUpdate=(task, index)=>{
array.munipulation
task.slice(0,index,index+1)
setTask([...oldTask,task])
}

const [isTask,setIstask] = React.useState(false)



const handleSubmit =( e)=>{
  e.prevenDefault()
  console.log(e)
}
  return (
    <>
//showCOmpleteTasks?

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <div>
        <form onSubmit={handleSubmit}>
        <label>
          Pick your favorite flavor:
          <select >
            <option value="task">Grapefruit</option>
            <option value="lime">Lime</option>
            <option value="coconut">Coconut</option>
            <option value="mango">Mango</option>
          </select>
        </label>
        <input type="submit" value="Submit" />
        <input type="submit" placeholder="group" value="Submit" />
      </form>
      </div>

<Groupcontainer>
groups.map(render groupCard group={group})

</Groupcontainer>

      </main>
    </>
  );
}



// 1. **Tasks** have a (1) name and (2) parent group. 
//     1. Users should be able to create, view, and complete tasks. Tasks should be displayed under their group.
//     2. Users should be able to move tasks between groups. 
// 2. **Groups** have a (1) name and (2) tasks. 
//     1. Tasks must belong to a group, but groups may be empty. 
//     2. Users should be able to create, view, and complete groups. 
// 3. By default, complete tasks and groups are hidden. A user can adjust a setting to show all tasks and groups.

    //    input is either task or group
    //    update state for new item
    //    render item in approb area

    // input
    // group container - hide/show tasks
    // task card
